### PR TITLE
fixed mac/linux, and added a default dialogue for npcs

### PR DESCRIPTION
**Pull request by Promises**

### CODE REVIEW

**Comment by Promises** [comment]
Remove the semicolon after the break in the firstclicknpc

**Comment by lare96** [comment]
Could I get you to remove the default NPC thing? Then I'll merge it in.

**Comment by Promises** [comment]
Hmm, 2 sec

**Comment by Promises** [comment]
Done.

**Comment by lare96** [comment]
Thanks.

**Pull request merged**
