### PR TITLE
Fixed graphic height and delay.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by atomicint** [comment]
Can you please submit this fix without formatting your files? I am unable to see specific changes because the entire file has been changed.

**Comment by lare96** [comment]
Could you please show me what specific lines you changed so I can add this in manually?

**Comment by ghost** [comment]
Edited the appendGraphic method to write two shorts, height and delay, rather than an int.

**Comment by lare96** [comment]
Thank you :)

**Pull request closed without merging**
